### ISSUE TITLE
Sponge Prism Error: Could not pass ChangeBlockEvent$Place$Impl

### ISSUE THREAD

**Issue by Sade66** [prism/Prism#101]
Hello,
We recently decided to update our modded server to Sponge and use Prism to track griefs. All was well until we had to remove a few region files from the world so the could be re-generated. Now Prism is spamming the console with the following [error](https://gist.github.com/Sade66/451f3a04714f5649c919b96d2342ad5e). We aren't sure what's causing it and any help is appreciated.

Thank you! :)

**Comment by viveleroi** [comment]
This isn't something we can fix. Essentially this means Sponge is trying to give us data about a block that has invalid/null data, which is most likely invalid data from a mod.

**Comment by fcpwiz** [comment]
@viveleroi Do you have any suggestions/troubleshooting ideas as how to resolve this? Even with a complete wipe of all Prism data, this issue still arises.

**Comment by viveleroi** [comment]
It's just a matter of finding which block/mod is causing the issue. 

You could:
- Compile Prism with a try/catch around this line https://github.com/prism/Prism/blob/master/src/main/java/com/helion3/prism/api/records/PrismRecord.java#L261 and looking at `transaction.getOriginal().getType().getId()`
- Run sponge/Prism in an IDE and debug that value
- Trial and error, remove mods until it stops.


Clearing Prism data won't affect this, because it's either Mod Data that has null/invalid content that Sponge is trying to export, or there's a bug inside Sponge, which isn't likely because it would be affecting every block.
