### ISSUE TITLE
Prism Broken

### ISSUE THREAD

**Issue by TheAloneOne** [prism/Prism#104]
Hello! I recently downloaded Prism and ran the 'gradlew.bat' and let everything download. At the end, I get this error:
https://i.imgur.com/qBzrAPi.png
Could anyone help me? Thanks.

My 'build.gradle' file: 
https://pastebin.com/EuLfrBLb

**Comment by viveleroi** [comment]
Without a stack trace I can't tell what the error actually was, but I can say that if you're trying to build Prism against SpongeAPI 7-snapshot it will fail because there were some breaking changes. I have an update ready I just need to test it.

**Comment by phit** [comment]
he downloaded the repo instead of cloning it, so its not a git repo anymore with makes the `build.gradle` die once `getVersionName` is called, which is pretty much the first thing
https://github.com/prism/Prism/blob/0b8c1fce698e835a9bb068518da7bb7b1248cfbe/build.gradle#L12-L21

**Comment by TheAloneOne** [comment]
So how would I fix this?

**Comment by phit** [comment]
properly clone the repo, or adjust the build.gradle to not rely on git for the version name

**Comment by viveleroi** [comment]
It doesn't seem like you intend to download the repo to begin with. This is the source code to Prism. If you want a built jar to run you can find those here: http://helion3.com:8080/job/Prism/

Otherwise if you *do* want the source, you'll need to clone the repo or strip the version piece from gradle like @phit suggested.

**Comment by TheAloneOne** [comment]
Thank you both very much!
