### ISSUE TITLE
Database disk usage is fairly high...

### ISSUE THREAD

**Issue by LemADEC** [prism/Prism#63]
After 5 weeks of usage on a small server (10 players or so), our Prism database have reach 12 GB of disk space. This is more than 8 weeks on a busy server (50 players or so) on 1.7.10.
Please consider updating database scheme to trim down disk usage.

This is with Prism-3.0.0-beta2-21-gdae772d-all.jar
![image](https://cloud.githubusercontent.com/assets/4776032/20285342/9de8986e-aac1-11e6-817f-2e3116da864b.png)

**Comment by viveleroi** [comment]
Prism is only supported on Sponge and does not use this schema.

**Comment by LemADEC** [comment]
Prism-3.0.0 is for Sponge and the database scheme I've shown is the one from Sponge.

For comparison, this is the Prism database scheme on 1.7.10 bukkit:
![image](https://cloud.githubusercontent.com/assets/4776032/20287382/6e3e2416-aacc-11e6-96fc-fbb7779f0419.png)

There's no 'water-flow' event to choose from on sponge 3.0.0.
Also, I don't see cleaning option like we used to have on bukkit:
```
  db-records-purge-rules:
  - before:8w
  - a:water-flow before:4w
```
hence we've no way to filter such spammy events.

**Comment by viveleroi** [comment]
I forgot how the mysql schema was setup then with 3.0. You can disable listeners via the config but listeners don't need nearly as much fine-tuning on Sponge, since they don't fire lame stuff like bukkit.

Prism for sponge is still in beta so there's no completed purge functionality for SQL databases. It's been started, but doesn't exist.

MySQL/H2 aren't the best database structures for Sponge because of how it works with data, that's why Mongo was the default and we're hoping to add Postgres. Mongo also supports record expiry.

**Comment by LemADEC** [comment]
My past experience with MongoDB, notably with Factions, discouraged me to use it. Moving to Sponge and 1.10 are enough pain as it is, without changing our DBMS.
