### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pocketpixelsmc** [prism/Prism#95]
Hi, so on start up I get this error: https://hastebin.com/siqegeyamu.sql

Then once started the console spams this error: https://hastebin.com/emijobiwuq.css

**Comment by viveleroi** [comment]
I can't reproduce the error. Using the latest build of Prism (set to H2) with the latest development build of SpongeForge. The error is occurring in `hikari.pool` though, which means whatever's causing it to fail is outside of Prism's control. There's no way to know what the cause is though, h2 is a file-based database so it could be disk permissions issues, etc.

If mysql/mongo are possibilities, I'd suggest trying those.
